# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LrxWZfZ5U8mrqtQH73W4ebbqIn9FspmE
"""

from flask import Flask, request, jsonify
from supabase import create_client
import os

app = Flask(__name__)

# Настройки Supabase
SUPABASE_URL = os.getenv("SUPABASE_URL")  # Замените на ваш URL
SUPABASE_KEY = os.getenv("SUPABASE_KEY")  # Замените на ваш API-ключ
supabase = create_client(SUPABASE_URL, SUPABASE_KEY)

@app.route("/judges", methods=["GET"])
def get_judges():
    response = supabase.table("judges").select("*").execute()
    return jsonify(response.data)

@app.route("/judges", methods=["POST"])
def add_judge():
    data = request.get_json()
    supabase.table("judges").insert(data).execute()
    return jsonify({"status": "success"}), 201

if __name__ == "__main__":
    app.run(debug=True)